#include "src/core/include/device.hpp"

#include <queue>

#define VK_PORTABILITY_SUBSET_NAME "VK_KHR_portability_subset"

#define VECS_GRAPHICS_QUEUE_BIT       0x1000000u
#define VECS_PRESENT_QUEUE_BIT        0x0100000u
#define VECS_SYNC_COMPUTE_QUEUE_BIT   0x0010000u
#define VECS_ASYNC_COMPUTE_QUEUE_BIT  0x0001000u
#define VECS_SYNC_TRANSFER_QUEUE_BIT  0x0000100u
#define VECS_ASYNC_TRANSFER_QUEUE_BIT 0x0000010u
#define VECS_SPARSE_QUEUE_BIT         0x0000001u

#define VECS_ALL_FAMILY       ( VECS_GRAPHICS_QUEUE_BIT | VECS_PRESENT_QUEUE_BIT | VECS_SYNC_COMPUTE_QUEUE_BIT | VECS_SYNC_TRANSFER_QUEUE_BIT )
#define VECS_COMPUTE_FAMILY   ( VECS_ASYNC_COMPUTE_QUEUE_BIT )
#define VECS_TRANSFER_FAMILY  ( VECS_ASYNC_TRANSFER_QUEUE_BIT )
#define VECS_ASYNC_FAMILY     ( VECS_ASYNC_COMPUTE_QUEUE_BIT | VECS_ASYNC_TRANSFER_QUEUE_BIT )
#define VECS_SPARSE_FAMILY    ( VECS_SPARSE_QUEUE_BIT )

namespace pp
{



} // namespace pp